spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql//localhost:3306/blog
    username: root
    password: 123



logging:
  level:
    root: info
    cn.wzheart: debug
  file: log/blog-dev.log

server:
  port: 80
